ROOT=$PWD
PREFIX=pkg/

BUILD_DIR=$ROOT/$PREFIX/build-release-x86_64
INSTALL_DIR=$BUILD_DIR/install

mkdir $BUILD_DIR

/Applications/CMake.app/Contents/bin/cmake -G Ninja \
	-DCMAKE_OSX_ARCHITECTURES=x86_64 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
	-DCMAKE_IGNORE_PREFIX_PATH="/opt/homebrew;/opt/homebrew/lib/cmake;/opt/homebrew/share/cmake/Modules;/opt/homebrew/Cellar/" \
	-DCMAKE_IGNORE_PATH="/opt/homebrew/Cellar/gdal/3.4.2/lib" \
	-DCMAKE_PREFIX_PATH="/usr/local/opt/qt@5;/usr/local/lib/cmake/usr/local/opt/cgal/lib/cmake" \
	-DCMAKE_CXX_FLAGS="-DDLIB_NO_GUI_SUPPORT -Wno-everything" \
	-DEIGEN_ROOT_DIR=/usr/local/include/eigen3 \
	-DCCCORELIB_USE_CGAL=ON \
	-DOPTION_USE_DXF_LIB=ON \
	-DOPTION_USE_SHAPE_LIB=ON \
	-DOPTION_USE_GDAL=ON \
	-DPLUGIN_GL_QEDL=ON \
	-DPLUGIN_GL_QSSAO=ON \
	-DPLUGIN_STANDARD_QANIMATION=ON \
	-DPLUGIN_STANDARD_QBROOM=ON \
	-DPLUGIN_STANDARD_QCANUPO=ON \
	-DPLUGIN_STANDARD_QCOLORIMETRIC_SEGMENTER=ON \
	-DPLUGIN_STANDARD_QCOMPASS=ON \
	-DPLUGIN_STANDARD_QCSF=ON \
	-DPLUGIN_STANDARD_QFACETS=ON \
	-DPLUGIN_STANDARD_QHOUGH_NORMALS=ON \
	-DPLUGIN_STANDARD_QHPR=ON \
	-DPLUGIN_STANDARD_QM3C2=ON \
	-DPLUGIN_STANDARD_QMPLANE=ON \
	-DPLUGIN_STANDARD_QPCL=ON \
	-DPLUGIN_STANDARD_QPCV=ON \
	-DPLUGIN_STANDARD_QPOISSON_RECON=ON\
	-DPLUGIN_STANDARD_QRANSAC_SD=ON \
	-DPLUGIN_STANDARD_QSRA=ON \
	-DPLUGIN_STANDARD_MASONRY_QAUTO_SEG=OFF \
	-DPLUGIN_STANDARD_MASONRY_QMANUAL_SEG=OFF \
	-DPLUGIN_STANDARD_QCLOUDLAYERS=ON \
	-DPLUGIN_IO_QCORE=ON \
	-DPLUGIN_IO_QADDITIONAL=ON \
	-DPLUGIN_IO_QCSV_MATRIX=ON \
	-DPLUGIN_IO_QE57=ON \
	-DPLUGIN_IO_QPDAL=ON \
	-DPLUGIN_IO_QPHOTOSCAN=ON \
	-S $ROOT \
	-B $BUILD_DIR 


BUILD_DIR=$ROOT/$PREFIX/build-release-arm64
INSTALL_DIR=$BUILD_DIR/install

mkdir $BUILD_DIR

/Applications/CMake.app/Contents/bin/cmake -G Ninja \
	-DCMAKE_OSX_ARCHITECTURES=arm64 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
	-DCMAKE_IGNORE_PREFIX_PATH="" \
	-DCMAKE_IGNORE_PATH="" \
	-DCMAKE_PREFIX_PATH="/opt/homebrew/Cellar/qt@5/5.15.3;" \
	-DCMAKE_CXX_FLAGS="-DDLIB_NO_GUI_SUPPORT -Wno-everything" \
	-DEIGEN_ROOT_DIR=/opt/homebrew/include/eigen3 \
	-DCCCORELIB_USE_CGAL=ON \
	-DOPTION_USE_DXF_LIB=ON \
	-DOPTION_USE_SHAPE_LIB=ON \
	-DOPTION_USE_GDAL=ON \
	-DPLUGIN_GL_QEDL=ON \
	-DPLUGIN_GL_QSSAO=ON \
	-DPLUGIN_STANDARD_QANIMATION=ON \
	-DPLUGIN_STANDARD_QBROOM=ON \
	-DPLUGIN_STANDARD_QCANUPO=ON \
	-DPLUGIN_STANDARD_QCOLORIMETRIC_SEGMENTER=ON \
	-DPLUGIN_STANDARD_QCOMPASS=ON \
	-DPLUGIN_STANDARD_QCSF=ON \
	-DPLUGIN_STANDARD_QFACETS=ON \
	-DPLUGIN_STANDARD_QHOUGH_NORMALS=ON \
	-DPLUGIN_STANDARD_QHPR=ON \
	-DPLUGIN_STANDARD_QM3C2=ON \
	-DPLUGIN_STANDARD_QMPLANE=ON \
	-DPLUGIN_STANDARD_QPCL=ON \
	-DPLUGIN_STANDARD_QPCV=ON \
	-DPLUGIN_STANDARD_QPOISSON_RECON=ON\
	-DPLUGIN_STANDARD_QRANSAC_SD=ON \
	-DPLUGIN_STANDARD_QSRA=ON \
	-DPLUGIN_STANDARD_QCLOUDLAYERS=ON \
	-DPLUGIN_STANDARD_MASONRY_QAUTO_SEG=OFF \
	-DPLUGIN_STANDARD_MASONRY_QMANUAL_SEG=OFF \
	-DPLUGIN_IO_QCORE=ON \
	-DPLUGIN_IO_QADDITIONAL=ON \
	-DPLUGIN_IO_QCSV_MATRIX=ON \
	-DPLUGIN_IO_QE57=ON \
	-DPLUGIN_IO_QPDAL=ON \
	-DPLUGIN_IO_QPHOTOSCAN=ON \
	-S $ROOT \
	-B $BUILD_DIR 


